# Use the official Golang image as a base image
FROM golang:1.18

# Set the working directory
WORKDIR /app

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy main.go and main_test.go
COPY main.go main_test.go ./

# Build the application
RUN go build -o main main.go

# Run tests
#RUN go test -v ./...

# Command to run the application
CMD ["./main"]